name: Test Windows Installer
on: [push]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4

    - name: Download Installer from Release
      run: |
        Invoke-WebRequest -Uri "https://github.com/chriswang06/DisderoPoExcelCreator/releases/download/release/DisderoPoExcelCreator-Setup.exe" -OutFile "installer.exe"

    - name: Test Installer
      timeout-minutes: 5
      run: |
        try {
          echo "Starting installation..."
          $process = Start-Process -FilePath ".\installer.exe" -ArgumentList "/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES" -Wait -PassThru -NoNewWindow
          
          if ($process.ExitCode -eq 0) {
            echo "Installation completed successfully"
          } else {
            echo "Installation failed with exit code: $($process.ExitCode)"
            exit 1
          }
        } catch {
          echo "Installation error: $($_.Exception.Message)"
          exit 1
        }

    - name: Verify Installation
      run: |
        # Check the CORRECT installation path (x86)
        if (Test-Path "C:\Program Files (x86)\DisderoPoExcelCreator\gui_app.py") {
          echo "✅ Installation successful - main files found"
        } else {
          echo "❌ Installation failed - gui_app.py missing"
          exit 1
        }
        
        # Check virtual environment
        if (Test-Path "C:\Program Files (x86)\DisderoPoExcelCreator\venv\Scripts\activate.bat") {
          echo "✅ Virtual environment created successfully"
        } else {
          echo "❌ Virtual environment missing"
          exit 1
        }
        
        echo "🎉 All installation checks passed!"

    - name: Test Application Launch (Optional)
      run: |
        try {
          $appPath = "C:\Program Files (x86)\DisderoPoExcelCreator\gui_app.py"
          $venvPython = "C:\Program Files (x86)\DisderoPoExcelCreator\venv\Scripts\python.exe"
          
          if ((Test-Path $appPath) -and (Test-Path $venvPython)) {
            echo "✅ Application files are accessible"
            # You could add more tests here like checking if dependencies are installed
            # & $venvPython -c "import tkinter; print('GUI framework available')"
          }
        } catch {
          echo "Warning: Could not test application launch: $($_.Exception.Message)"
        }