name: Test Windows Installer
on: [push]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 15  # Prevent hanging for hours
    steps:
    - uses: actions/checkout@v4  # Updated to latest version

    - name: Download Installer from Release
      run: |
        # Replace with your actual release URL
        Invoke-WebRequest -Uri "https://github.com/chriswang06/DisderoPoExcelCreator/releases/download/release/DisderoPoExcelCreator-Setup.exe" -OutFile "installer.exe"
        
        # Verify download
        if (!(Test-Path "installer.exe")) {
          echo "Failed to download installer"
          exit 1
        }
        
        $fileSize = (Get-Item "installer.exe").Length
        echo "Downloaded installer size: $fileSize bytes"

    - name: Test Installer
      timeout-minutes: 10  # Step-level timeout
      run: |
        try {
          # Try multiple silent installation flags
          $processArgs = @{
            FilePath = ".\installer.exe"
            ArgumentList = @("/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES", "/FORCECLOSEAPPLICATIONS")
            Wait = $true
            PassThru = $true
            NoNewWindow = $true
          }
          
          echo "Starting installation with arguments: $($processArgs.ArgumentList -join ' ')"
          $process = Start-Process @processArgs
          
          # Check exit code
          if ($process.ExitCode -eq 0) {
            echo "Installer completed with exit code 0"
          } else {
            echo "Installer failed with exit code: $($process.ExitCode)"
            exit 1
          }
          
        } catch {
          echo "Error running installer: $($_.Exception.Message)"
          exit 1
        }

    - name: Verify Installation
      run: |
        # Check if installation completed
        $mainFile = "C:\Program Files\DisderoPoExcelCreator\gui_app.py"
        $venvFile = "C:\Program Files\DisderoPoExcelCreator\venv\Scripts\activate.bat"
        
        if (Test-Path $mainFile) {
          echo "✓ Installation successful - main files found"
        } else {
          echo "✗ Installation failed - main files missing at: $mainFile"
          
          # Debug: List what was actually installed
          $programFiles = "C:\Program Files\DisderoPoExcelCreator"
          if (Test-Path $programFiles) {
            echo "Contents of installation directory:"
            Get-ChildItem $programFiles -Recurse | Select-Object FullName
          } else {
            echo "Installation directory not found: $programFiles"
          }
          exit 1
        }
        
        if (Test-Path $venvFile) {
          echo "✓ Virtual environment created"
        } else {
          echo "✗ Virtual environment missing at: $venvFile"
          exit 1
        }
        
        echo "All installation checks passed!"

    - name: Test Application Launch (Optional)
      run: |
        # Optional: Try to run the application briefly to ensure it works
        try {
          $appPath = "C:\Program Files\DisderoPoExcelCreator\gui_app.py"
          if (Test-Path $appPath) {
            # Activate venv and try to run (with timeout)
            $venvActivate = "C:\Program Files\DisderoPoExcelCreator\venv\Scripts\activate.bat"
            if (Test-Path $venvActivate) {
              echo "Testing application launch..."
              # This is just a basic check - adjust based on your app's behavior
              # You might want to add --help flag or similar to avoid GUI startup
            }
          }
        } catch {
          echo "Warning: Could not test application launch: $($_.Exception.Message)"
          # Don't fail the build for this optional step
        }