name: Test Windows Installer
on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download Installer from Release
      run: |
        # Replace with your actual release URL
        Invoke-WebRequest -Uri "https://github.com/chriswang06/DisderoPoExcelCreator/releases/download/release/DisderoPoExcelCreator-Setup.exe" -OutFile "installer.exe"

    - name: Test Installer
      run: |
        # Run installer silently
        Start-Process -FilePath ".\installer.exe" -ArgumentList "/SILENT" -Wait
        
        # Check if installation completed
        if (Test-Path "C:\Program Files\DisderoPoExcelCreator\gui_app.py") {
          echo "Installation successful"
        } else {
          echo "Installation failed - main files missing"
          exit 1
        }
        
        # Check virtual environment
        if (Test-Path "C:\Program Files\DisderoPoExcelCreator\venv\Scripts\activate.bat") {
          echo "Virtual environment created"
        } else {
          echo "Virtual environment missing"
          exit 1
        }