name: Build Windows Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build exe with PyInstaller
      run: |
        pyinstaller --name="DisderoPoExcelCreator" `
          --onefile `
          --windowed `
          --add-data="productslist.xlsx;." `
          --add-data="src;src" `
          --clean `
          gui_app.py

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: DisderoPoExcelCreator-exe
        path: dist/DisderoPoExcelCreator.exe

    - name: Build installer with Inno Setup
      run: |
        # Download Inno Setup
        Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup.exe"
        
        # Install Inno Setup silently
        Start-Process -FilePath ".\innosetup.exe" -ArgumentList "/VERYSILENT", "/NORESTART" -Wait
        
        # Build installer
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: DisderoPoExcelCreator-installer
        path: output/DisderoPoExcelCreator-Setup.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/DisderoPoExcelCreator.exe
          output/DisderoPoExcelCreator-Setup.exe
        draft: false
        prerelease: false